import path from "node:path";
import fsp from "node:fs/promises";
import { ensureDir, writeFileAtomic } from "../filesystem";

export async function saveAnswerAsPage(input: {
  project_path: string;
  question: string;
  answer: string;
  page_title: string;
  category?: "synthesis" | "entity" | "concept" | "timeline";
  source_page_ids?: string[];
}): Promise<{
  saved_page_id: string;
  saved_path: string;
  category: string;
  error?: string;
}> {
  try {
    const projectPath = path.resolve(input.project_path);
    const docuDir = path.join(projectPath, ".docuflow");
    const wikiDir = path.join(docuDir, "wiki");

    // Use provided category or default to synthesis
    const category = input.category ?? "synthesis";
    const categoryDir = path.join(wikiDir, category + "s");
    await ensureDir(categoryDir);

    // Generate page ID from title
    const pageId = `query_${input.page_title
      .toLowerCase()
      .replace(/[^a-z0-9]/g, "_")
      .replace(/_+/g, "_")
      .substring(0, 50)}`;

    // Generate frontmatter
    const now = new Date().toISOString();
    const sources = input.source_page_ids ?? [];
    const frontmatterYaml = `---
created_at: ${now}
updated_at: ${now}
sources: ${JSON.stringify(sources)}
tags: ["query_result","synthesis"]
inbound_links: ${JSON.stringify([])}
outbound_links: ${JSON.stringify(sources)}
---
`;

    // Build page content
    const pageContent = `${frontmatterYaml}
# ${input.page_title}

**Generated from query**: ${input.question}

**Synthesis timestamp**: ${now}

## Answer

${input.answer}

## Related Pages

${
  sources.length > 0
    ? sources.map((s) => `- [\`${s}\`](../CATEGORY/${s}.md)`).join("\n")
    : "No source pages linked."
}

---

*This page was generated by synthesizing answers from multiple wiki pages.*
*To refine further, add more source documents and re-ingest.*
`;

    // Write the page file
    const pageFile = path.join(categoryDir, `${pageId}.md`);
    const bytes = await writeFileAtomic(pageFile, pageContent);

    // Also update log.md to record this
    const logFile = path.join(docuDir, "log.md");
    try {
      let logContent = "";
      try {
        const logRead = await fsp.readFile(logFile, "utf-8");
        logContent = logRead;
      } catch (e) {
        logContent = "# Operation Log\n\n";
      }

      const timestamp = now.split("T")[0]; // YYYY-MM-DD
      const logEntry = `## [${timestamp}] query-result | Saved answer as ${pageId}\n\n`;
      logContent += logEntry;

      await writeFileAtomic(logFile, logContent);
    } catch (e) {
      // Log update failure is not critical
    }

    return {
      saved_page_id: pageId,
      saved_path: path.relative(docuDir, pageFile),
      category,
    };
  } catch (e: any) {
    return {
      saved_page_id: "",
      saved_path: "",
      category: input.category ?? "synthesis",
      error: e?.message ?? String(e),
    };
  }
}
